openapi: 3.0.0
info:
  title: Payment API
  description: API for handling payments with Stripe
  version: 1.0.0
paths:
  /create-checkout-session:
    post:
      summary: Create a checkout session
      description: |
        Endpoint to create a checkout session with Stripe.
      tags:
        - Payment
      security:
        - userAccess: []
      requestBody:
        required: false
        content:
          application/json: {}
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /checkout-success:
    get:
      summary: Handle successful checkout
      description: |
        Endpoint to handle successful checkout with Stripe.
      tags:
        - Payment
      security:
        - userAccess: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /checkout-cancel:
    get:
      summary: Handle cancelled checkout
      description: |
        Endpoint to handle cancelled checkout with Stripe.
      tags:
        - Payment
      security:
        - userAccess: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

securitySchemes:
  userAccess:
    type: apiKey
    in: header
    name: Authorization
