const EErrors = {
    CART_NOT_FOUND: 1,
    PRODUCT_NOT_FOUND: 2,
    PRODUCT_NOT_AVAILABLE: 3,
    FORBIDDEN_ACCESS: 4,
    PRODUCT_ALREADY_EXISTS: 5,
    USER_DOES_NOT_EXIST: 6,
    PASSWORD_NOT_VALID: 7,
    NOT_AUTOHORIZED: 8,
  };
  export default EErrors;